INSERT INTO cenipa.aeronave
VALUES 
(80469, 'PPGFC','***', 'AVIÃO', 'AERO BOERO', 'AB-115', 'AB11', 'PISTÃO', 'MONOMOTOR', 770, 770, 3, 1992, 'BRASIL','BRASIL', 'AVIÃO', 'PARTICULAR', 'FAZENDA SANTO ÂNGELO', 'POUSO ALEGRE', 'POUSO', 'INSTRUÇÃO', 'SUBSTANCIAL',2);